apiVersion: v1
kind: PersistentVolume
metadata:
  name: pedidos-pv
  labels:
    app: pedidos
    component: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pedidos