apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pedidos-pvc
  labels:
    app: pedidos
    component: storage

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi